server:
  port: 8082
  error:
    include-message: always

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/inventory_management
    username: n
    password: n
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

security:
  jwt:
    secret-key: "WXw75pu6zkeJz2fOIXuxX6ogL9kiakA5kM6hmrsFEpE="
    expiration-time: 10,800,000  # 3 hours in milliseconds

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    biz.technway.khaled.inventorymanagementapi: TRACE