server:
  port: 8082
  error:
    include-message: always

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: n
    url: jdbc:mysql://localhost:3306/inventory_management
    password: n
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true