server:
  port: 8082
  error:
    include-message: always

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/inventory_management
    username: n
    password: n
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

#security:
#  jwt:
#    secret-key: "your-256-bit-secret-key-in-base64"
#    expiration-time: 3600000  # 1 hour in milliseconds
